modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/Raided/issues"
license="MIT"

[[mods]]
modId="raided"
version="${file.jarVersion}"
displayName="Raided"
displayURL="https://www.curseforge.com/minecraft/mc-mods/raided"
authors="Mrbysco, silentine"
description='''
Expands upon the vanilla raid system to allow for more advanced raid mechanics.
'''
[[dependencies.raided]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.raided]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.70-beta,)"
ordering="NONE"
side="BOTH"